### PR TITLE
Rjdev

### PR DESCRIPTION
**Pull request by rjovelin**

### CODE REVIEW

**Comment by rjovelin** [comment]
test this please

**Comment by rjovelin** [comment]
test this please

**Comment by rjovelin** [comment]
test this please

**Comment by rjovelin** [comment]
test this please

**Comment by lheisler** [comment]
the README.md file should be generated using
>module load gsi-wdl-tools
>generate-markdown-readme --input-wdl-path

however, the version of gsi-wdl-tools is being updated, to remove references to Niassa

Mike informed me it will be ready soon
gsi-wdl-tools/20210730

**Review by lheisler — APPROVED** [review]
see comment regarding the README, otherwise approving

**Review by xuemeiluo — APPROVED** [review]

**Pull request merged**
